uPortal-Project/uPortal-web-components

@uportal/content-carousel/package.json
@uportal/content-carousel/test/unit/App.spec.js
@uportal/open-id-connect/README.md
@uportal/open-id-connect/package.json
@uportal/open-id-connect/src/open-id-connect.js
@uportal/open-id-connect/src/open-id-connect.spec.js
package.json
yarn.lock

Offers a shared Open ID Connect helper to get an auth token, and hold on to the auth token until it expires.

feat(open-id-connect): create shared oidc helper for uPortal

---

@uportal/content-carousel/src/App.vue

feat(content-carousel): add better styles for the content objects

---

@uportal/open-id-connect/package.json
@uportal/open-id-connect/src/open-id-connect.js
yarn.lock

/cc @jonathanmtran this automatically adds
```
require('regenerator-runtime/runtime');
```
to the output

fix: ensure polyfills are included with open id connect helper

---

.travis.yml
@uportal/content-carousel/package.json
@uportal/content-carousel/test/unit/App.spec.js
@uportal/open-id-connect/package.json
yarn.lock

Test: fix tests

---

CHANGELOG.md
README.md
docs/en/README.md
docs/en/components/README.md
docs/en/developer/AUTOMATION.md
docs/en/developer/VUE-COMPONENT.md

docs: guide to creating a new vue web component

---

.travis.yml
@uportal/content-carousel/package-lock.json
@uportal/open-id-connect/package-lock.json
@uportal/open-id-connect/package.json
package-lock.json

includes work around for https://github.com/facebook/jest/issues/6766

chore: update node modules

---

@uportal/content-carousel/src/App.ts
@uportal/content-carousel/src/components/ContentCarousel.ts
@uportal/waffle-menu/README.md
@uportal/waffle-menu/package-lock.json
@uportal/waffle-menu/package.json
@uportal/waffle-menu/public/index.html
@uportal/waffle-menu/src/WaffleMenu.js
CHANGELOG.md
docs/en/components/content-carousel/README.md
docs/en/components/waffle-menu/README.md

- Drops category attribute on waffle-menu
- Fully configurable URL through the url attribute
- Fixes button color
- Adds in local development features (proxy)
- Adjust README to match changes

fix: formatting and display

---

@uportal/portlet-registry-to-array/package-lock.json
@uportal/portlet-registry-to-array/package.json
@uportal/portlet-registry-to-array/src/portlet-registry-to-array.js
@uportal/waffle-menu/public/index.html

- boils out all duplicates within portlet array.

fix: data processing

---

@uportal/waffle-menu/src/WaffleMenu.js

Re-style waffle menu component and position

---

.travis.yml
@uportal/content-carousel/package-lock.json
@uportal/content-carousel/package.json
@uportal/waffle-menu/package-lock.json
CHANGELOG.md
docs/en/developer/SETUP.md
lerna.json
package-lock.json
package.json

use `npm start` for vue local web server.
ensure package lock files are in sync with package json.
require a newer version of node by default.
resolves #68

docs: update setup documentation

---

@uportal/content-carousel/src/App.ts
@uportal/waffle-menu/.eslintrc
@uportal/waffle-menu/README.md
@uportal/waffle-menu/public/index.html
@uportal/waffle-menu/src/WaffleMenu.js
CHANGELOG.md
docs/en/components/waffle-menu/demo.html

Added the ability to supply a menu background color. Docs and demo updated as well.

feat: menu background color

---

@uportal/content-carousel/public/empty.rss
@uportal/content-carousel/src/App.vue
@uportal/content-carousel/src/components/ContentCarousel.html
@uportal/content-carousel/src/components/ContentCarousel.scss
@uportal/content-carousel/src/components/ContentCarousel.vue

feat: support slotted field for empty results

---

@uportal/content-carousel/README.md
CHANGELOG.md
docs/en/components/content-carousel/README.md
docs/en/components/content-carousel/demo.html

vue web components do not support self closing tags.

fix: web component docs for content carousel

---

@uportal/content-carousel/package-lock.json
@uportal/content-carousel/package.json
@uportal/content-carousel/src/App.ts
@uportal/content-carousel/src/App.vue
@uportal/content-carousel/src/components/ContentCarousel.html
@uportal/content-carousel/src/components/ContentCarousel.scss
@uportal/content-carousel/src/components/ContentCarousel.ts

- add text align property to component
- modified non-hero templates per @drewwills

Carousel template changes

---

@uportal/content-carousel/README.md
@uportal/content-carousel/src/App.scss
@uportal/content-carousel/src/App.vue
@uportal/content-carousel/src/components/ContentCarousel.html
@uportal/content-carousel/src/components/ContentCarousel.ts
docs/en/components/content-carousel/README.md
docs/en/components/content-carousel/demo.html
package.json

See documentation included in updated component README
resolves https://github.com/uPortal-contrib/uPortal-web-components/issues/63

feature: header and slide slots

---

@uportal/content-carousel/package.json
@uportal/content-carousel/src/lib/PortletStrategy.ts
@uportal/waffle-menu/package.json
@uportal/waffle-menu/src/WaffleMenu.js
CHANGELOG.md
lerna.json

fix: support alternative maximized links

---

@uportal/content-carousel/vue.config.js
@uportal/eyebrow-user-info/vue.config.js

based off fixes in https://github.com/Jasig/NotificationPortlet/pull/111

fix: automatically polyfill open-id-connect helper for vue components

---

@uportal/content-carousel/src/App.scss
@uportal/content-carousel/src/App.vue
@uportal/content-carousel/src/components/ContentCarousel.html
@uportal/content-carousel/src/components/ContentCarousel.scss

fix: content carousel is-responsive-to-container display now has no margin

---

@uportal/esco-content-menu/src/components/ActionFavorites.vue
@uportal/esco-content-menu/src/components/ContentMenu.vue
@uportal/esco-content-menu/src/components/ContentUser.vue
@uportal/esco-content-menu/src/components/PortletCard.vue
@uportal/esco-content-menu/src/i18n.js
@uportal/eyebrow-user-info/src/components/EyebrowUserInfo.vue
@uportal/eyebrow-user-info/src/i18n.js
@uportal/waffle-menu/src/WaffleMenu.js
package-lock.json
package.json

Holding off on create react update for now

chore: update top level dependencies

---

@uportal/esco-content-menu/package-lock.json
@uportal/eyebrow-user-info/package-lock.json
@uportal/open-id-connect/package-lock.json
@uportal/open-id-connect/package.json
@uportal/open-id-connect/src/open-id-connect.js
@uportal/waffle-menu/public/index.html
docs/en/components/content-carousel/demo.html
docs/en/components/waffle-menu/demo.html

Reduces bundle size and will ensure network calls do not block the main thread in newer browsers.

refactor: drop axios as dependency of open id connect helper, use fetch

---

@uportal/esco-content-menu/src/components/ContentGrid.vue
@uportal/esco-content-menu/src/components/PortletCard.vue

This intends to offer a more flexible extension to the current `is-small` property, offering ability to create new sizes easily.

feat: support sizing system in content grid and portlet card

---

@uportal/content-carousel/src/components/ContentCarousel.html

fix(content-carousel): open links in new tab by default

---

docs/en/developer/RELEASE.md
package-lock.json
package.json

add lerna-webjar to automatically start webjar releases on webjars.org

build: automate webjar release

---

@uportal/esco-content-menu/package-lock.json
@uportal/esco-content-menu/package.json
@uportal/esco-content-menu/src/components/ActionFavorites.vue
@uportal/esco-content-menu/src/components/ContentFavorites.vue
@uportal/esco-content-menu/src/components/ContentUser.vue
@uportal/esco-content-menu/src/components/HeaderButtons.vue
@uportal/esco-content-menu/src/icons.js

fix on font-awesome icons, the icons helper wasn't applied on each components ! All imports into App.vue are only used on `npm run start`, for compiled components you need to re-import it on each components.vue when it's needed

fix(esco-content-menu): icons problems

---

@uportal/content-carousel/README.md
@uportal/content-carousel/package.json
docs/en/components/content-carousel/README.md
docs/en/components/content-carousel/demo.html

stylesheet is needed to correctly apply font face needed by the component.
resolves #85
closes #146

build: bundle slick theme with package

---

@uportal/esco-content-menu/src/App.vue
@uportal/esco-content-menu/src/components/ActionFavorites.vue
@uportal/esco-content-menu/src/components/ContentFavorites.vue
@uportal/esco-content-menu/src/components/ContentGrid.vue
@uportal/esco-content-menu/src/components/ContentMenu.vue
@uportal/esco-content-menu/src/components/ContentUser.vue
@uportal/esco-content-menu/src/components/PortletCard.vue
@uportal/esco-content-menu/src/services/sizeTools.js
@uportal/esco-content-menu/src/styles/vars.scss

Some change in progress: 
- review the isSmall property. 
- provide a new way of favorite-content. 
- some fix
Mainly UI change.

Reviewing isSmall to different size

---

@uportal/content-carousel/package-lock.json
@uportal/esco-content-menu/package-lock.json
@uportal/eyebrow-user-info/package-lock.json
@uportal/open-id-connect/package-lock.json
@uportal/portlet-registry-to-array/package-lock.json
@uportal/waffle-menu/package-lock.json
package-lock.json
package.json

update package lockfile for all packages

chore: update lint staged to version 8

---

@uportal/esco-content-menu/src/components/ContentGrid.vue
@uportal/esco-content-menu/src/locales/en.json
@uportal/esco-content-menu/src/locales/fr.json

Firefox 63 as a bug on datalist integrated into web-components. This is a fix moving from datalist to select. The comportment is better and doesn't depend on the browser...

fix(content-menu): datalist to select to avoid firefox bugs

---

@uportal/esco-content-menu/package-lock.json
@uportal/esco-content-menu/src/components/ContentGrid.vue

Provide a better css managment for small devices on search inputs

fix(content-menu): better css management on search inputs for sm devices

---

@uportal/content-carousel/package.json

fix(content-carousel): copy fonts into distribution package

---

@uportal/esco-content-menu/src/components/ContentGrid.vue
@uportal/esco-content-menu/src/components/ContentMenu.vue
@uportal/esco-content-menu/src/services/fetchPortlets.js

refactor: return values from fetch portlets helper, instead of `this`

---

@uportal/content-carousel/README.md
@uportal/content-carousel/public/index.html
@uportal/content-carousel/src/components/ContentCarousel.html
@uportal/esco-content-menu/README.md
@uportal/esco-content-menu/public/index.html
@uportal/eyebrow-user-info/README.md
@uportal/eyebrow-user-info/public/index.html
@uportal/waffle-menu/README.md
@uportal/waffle-menu/public/index.html
docs/en/components/content-carousel/README.md
docs/en/components/content-carousel/demo.html
docs/en/components/waffle-menu/README.md
docs/en/components/waffle-menu/demo.html
package-lock.json
package.json

Prettier can now format html files and inline html code blocks.
https://prettier.io/blog/2018/11/07/1.15.0.html

style: prettier html

---

@uportal/esco-content-menu/package-lock.json
@uportal/esco-content-menu/package.json
@uportal/esco-content-menu/src/components/Ellipsis.vue
@uportal/esco-content-menu/src/services/fetchFavorites.js
@uportal/esco-content-menu/src/services/fetchPortlets.js

Fix on favorites and portlets helpers to return empty arrays on errors

fix(esco-content-menu): fix fetch helpers

---

@uportal/esco-content-menu/package-lock.json
@uportal/esco-content-menu/package.json
@uportal/esco-content-menu/src/components/ContentMenu.vue

This feature add a spinner during all fetch are resolved. Only available on content-menu component.
Warning this is based on #173

feat(esco-content-menu): adding spinner during fetch

---

@uportal/esco-content-menu/src/components/PortletCard.vue

fix bad use of ng-if instead of v-if

fix(esco-content-menu): used ng-if instead of v-if

---

@uportal/esco-content-menu/README.md
@uportal/esco-content-menu/src/components/ContentGrid.vue

feat(esco-content-menu): add hide-title attribute option

---

@uportal/esco-content-menu/src/components/ContentGrid.vue

fix(esco-content-grid): remove small(er) background color

---

@uportal/esco-content-menu/README.md
@uportal/esco-content-menu/src/components/ContentGrid.vue
@uportal/esco-content-menu/src/components/ContentGridFilter.vue

feat(esco-content-grid): add external category grid filter

---

@uportal/dashboard-carousel/README.md

[![NPM Version](https://img.shields.io/npm/v/@uportal/dashboard-carousel.svg)](https://www.npmjs.com/package/@uportal/dashboard-carousel)
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/org.webjars.npm/uportal__dashboard-carousel/badge.svg)](https://maven-badges.herokuapp.com/maven-central/org.webjars.npm/uportal__dashboard-carousel)
[![Build Status](https://travis-ci.org/uPortal-contrib/uPortal-web-components.svg?branch=master)](https://travis-ci.org/uPortal-contrib/uPortal-web-components)

docs(dashboard-carousel): add npm, maven, and ci badges to readme

---

@uportal/esco-content-menu/src/components/ContentGrid.vue
@uportal/esco-content-menu/src/components/ContentGridFilter.vue

fix(content-grid-filter): fix event name and styling

---

@uportal/dashboard-carousel/src/components/DashboardCarousel.vue
@uportal/dashboard-carousel/src/components/PortletRenderer.vue

This will allow the dashboard carousel to be run in demo/debug mode without uPortal running

fix(dashboard-carousel): debug mode

---

docs/en/developer/create-web-component/VUE.md

This PR contains documentation updates based on insights from a recent experience releasing a new component.
- Several small steps have been added
- _Additional Steps for Web Components in `uPortal-web-components` (This Project)_ has been split into its own section (below)

docs: enhance instructions for creating a component with Vue

---

@uportal/dashboard-carousel/public/example-portlet.html
@uportal/dashboard-carousel/public/layout.json

Updated appearance running only with Node.js

docs: include example html for portlet

---

@uportal/api-template-vue/src/App.vue

style(api-template-vue): modify table to description

---

@uportal/dashboard-carousel/src/components/DashboardCarousel.vue

fix(dashboard-carousel): set list width to 100 percent

---

docs/en/developer/create-web-component/VUE.md
docs/fr/developer/create-web-component/VUE.md

docs(vue.md): provide the french translation of vue.js guide + fix in title hierarchy in the english doc

---

package.json

chore: enable renovate lockfile maintainance

---

docs/en/developer/create-web-component/VUE.md

Cleaned up Vue.MD and added an appendix item to explain how to do a quick rebuild without having to restart uPortal in order to speed up development. See how it looks [here](https://github.com/laurenra7/uPortal-web-components/blob/master/docs/en/developer/create-web-component/VUE.md) if it's difficult to see the differences in the pull request.

cleaned up VUE.md and added quick build instructions

---

docs/en/developer/RELEASE.md

Additional helpful details about the `npm run publish-webjar` process.

docs: enhance info about publish-webjar

---

package-lock.json
package.json

CLI will now show which are in progress, which are completed, and which have failed.
```
⠙ publishing @uportal/api-template-vue
⠙ publishing @uportal/content-carousel
⠙ publishing @uportal/dashboard-carousel
⠙ publishing @uportal/esco-content-menu
✔ publishing @uportal/eyebrow-user-info
✔ publishing @uportal/open-id-connect
✔ publishing @uportal/portlet-registry-to-array
⠙ publishing @uportal/user-profile-menu
⠙ publishing @uportal/waffle-menu
````

chore: update lerna webjar package for better status reporting

---

@uportal/api-template-vue/src/App.vue
@uportal/content-carousel/README.md
@uportal/content-carousel/src/App.vue
@uportal/content-carousel/src/components/ContentCarousel.vue
@uportal/esco-content-menu/package-lock.json
@uportal/esco-content-menu/package.json
@uportal/esco-content-menu/src/App.vue
@uportal/esco-content-menu/src/components/ActionFavorites.vue
@uportal/esco-content-menu/src/components/ContentGrid.vue
@uportal/esco-content-menu/src/components/ContentMenu.vue
@uportal/esco-content-menu/src/components/ContentUser.vue
@uportal/esco-content-menu/src/components/HamburgerMenu.vue
@uportal/esco-content-menu/src/components/HeaderButtons.vue
@uportal/esco-content-menu/src/components/PortletCard.vue
@uportal/eyebrow-user-info/src/App.vue
@uportal/eyebrow-user-info/src/components/EyebrowUserInfo.vue
docs/en/components/content-carousel/README.md
docs/en/components/content-carousel/demo.html
docs/fr/components/content-carousel/README.md
docs/fr/components/content-carousel/demo.html

leverages https://github.com/kentcdodds/match-sorter to support partial matches, abbreviations, and result ranking in search.
:art: also in this PR, the source code was run code through latest prettier formatter version.
Category search
Term Search and Ranking
Abbreviation Search and Ranking

feat(esco-content-menu): support partial term matching and ranking

---

@uportal/user-profile-menu/src/components/ProfileMenu.vue

Set object-fit image to size to its container.

fix: fixed scaling of large user profile images

---

.travis.yml
@uportal/api-template-vue/package-lock.json
@uportal/content-carousel/package-lock.json
@uportal/dashboard-carousel/package-lock.json
@uportal/esco-content-menu/package-lock.json
@uportal/eyebrow-user-info/package-lock.json
@uportal/open-id-connect/package-lock.json
@uportal/portlet-registry-to-array/package-lock.json
@uportal/user-profile-menu/package-lock.json
@uportal/waffle-menu/package-lock.json
lerna.json
package-lock.json
package.json

React is no longer used in any of the components in this project.

test: remove eslint react

---

@uportal/esco-content-menu/src/components/ActionFavorites.vue
@uportal/esco-content-menu/src/components/ContentFavorites.vue
@uportal/esco-content-menu/src/components/ContentGrid.vue

Added a dom event fired to let other components know when the favorites are updated. Also fixed a props issue in ContentFavorites.vue

feat: added dom event to reload on favorites update

---

@uportal/content-carousel/public/index.html
@uportal/content-carousel/src/App.scss
@uportal/content-carousel/src/App.vue
@uportal/content-carousel/src/components/ContentCarousel.scss
@uportal/content-carousel/src/components/ContentCarousel.ts

Added customizable css vars to content carousel to control arrows

feat: content carousel css vars

---

@uportal/esco-content-menu/src/components/ContentGrid.vue

feat: update esco-content-grid to opt out of external filtering

---

@uportal/content-carousel/public/portletRegistry.json
@uportal/content-carousel/src/lib/PortletStrategy.ts

title is the public name while name is the internal name

fix(content-carousel): updated portlet strategy to use title

---

@uportal/esco-content-menu/src/components/ActionFavorites.vue

fix(esco-content-grid): added context to favorite button

---

@uportal/esco-content-menu/src/components/ActionFavorites.vue

follow-up to #427 and resolves #426

fix(esco-content-grid): restored and moved title attribute to favorite btn

---

.github/workflows/CI.yml
README.md

Run the full test suite on GitHub actions for open source
https://github.com/features/actions

ci: setup github actions ci

---

@uportal/esco-content-menu/README.md
@uportal/esco-content-menu/src/components/ContentMenu.vue
@uportal/esco-content-menu/src/components/ContentUser.vue
@uportal/esco-content-menu/src/components/HamburgerMenu.vue
docs/en/components/esco-content-menu/README.md
docs/fr/components/esco-content-menu/README.md

Add a property to be able to provide an ability to have an overview of the new Organization Logo before to update it to all peoples

feat: force org logo

---

@uportal/eyebrow-user-info/src/components/EyebrowUserInfo.vue

linter update added an img extra tag

fix: extra html tag added after linter update

---

@uportal/sidebar-nav/package.json

fix: add repo url and other metadata

---

@uportal/esco-content-menu/README.md
@uportal/esco-content-menu/src/components/ActionFavorites.vue
docs/en/components/esco-content-menu/README.md
docs/fr/components/esco-content-menu/README.md

Request to add color customization on favorite icon.
Also fix doc header + provide doc on new CSS var

feat(esco-content-menu): add var on color

---

@uportal/dashboard-carousel/README.md
docs/en/developer/uportal-demo/README.md
docs/en/developer/uportal-demo/dash-car-demo-lo.fragment-definition.xml
docs/en/developer/uportal-demo/dash-car-demo-lo.fragment-layout.xml
docs/en/developer/uportal-demo/dash-car-demo-lo.xml

Adding the data files and quick guide to get up and running with the dashboard carousel in uPortal-start

Add a dashboard carousel uportal demo

---

@uportal/content-carousel/README.md
@uportal/content-carousel/package.json
@uportal/content-renderer/README.md
@uportal/dashboard-carousel/README.md
@uportal/esco-content-menu/README.md
@uportal/eyebrow-user-info/README.md
@uportal/open-id-connect/package.json
@uportal/portlet-registry-to-array/package.json
@uportal/sidebar-nav/package.json
@uportal/waffle-menu/README.md
@uportal/waffle-menu/package.json
docs/en/components/content-carousel/README.md
docs/en/components/dashboard-carousel/README.md
docs/en/components/esco-content-menu/README.md
docs/en/components/eyebrow-user-info/README.md
docs/en/components/waffle-menu/README.md
docs/fr/components/content-carousel/README.md
docs/fr/components/dashboard-carousel/README.md
docs/fr/components/esco-content-menu/README.md
docs/fr/components/eyebrow-user-info/README.md
docs/fr/components/waffle-menu/README.md

Update to the new repository url for documentation

doc: update new github repository url

---

@uportal/open-id-connect/package-lock.json
@uportal/open-id-connect/package.json
@uportal/open-id-connect/rollup.config.js
@uportal/open-id-connect/src/open-id-connect.js
@uportal/portlet-registry-to-array/package-lock.json
@uportal/portlet-registry-to-array/package.json
@uportal/portlet-registry-to-array/rollup.config.js

Issue loading modules with changes to rollup

fix: add rollup node resolve plugin for extern modules

---

@uportal/esco-content-menu/src/components/ContentGrid.vue

Categories need to wait for fetching portlet data to be received.

fix(esco-grid): fix categories

---

@uportal/dashboard-carousel/public/layout.json
@uportal/dashboard-carousel/src/components/Carousel.vue

Adds support for a MAINTENANCE lifecycleState to the Dashboard Carousel widget

feat: added support for maintenance mode
