uPortal-Project/uPortal-web-components

COMMITTERS.md

Documents that Committers modeled as specific team, 
which may help remind on future committer add to also update the team.

Noted that committers modeled as GitHub team

---

@uportal/content-carousel/package.json
CHANGELOG.md

Resolves warning 'browser dead is not recognized', this query will be supported in a later version of vue/babel.

Build: vue browserslist fix

---

@uportal/open-id-connect/.babelrc
@uportal/open-id-connect/package-lock.json
@uportal/open-id-connect/package.json
@uportal/open-id-connect/src/open-id-connect.js

This results in babel-polyfill is already defined warnings and page bloat.
Instead let implementors apply polyfills as wanted/needed.
/cc @jgribonvald @mrapczynski @jonathanmtran

fix(open-id-connect): do not embed polyfills with script

---

@uportal/content-carousel/package-lock.json
@uportal/content-carousel/package.json
@uportal/content-carousel/src/components/ContentCarousel.html
@uportal/content-carousel/src/components/ContentCarousel.ts

vue-slick does not watch for mutations on it's content, meaning it needs to be alerted when changes happen.
the recommended way, `reslick` is currently broken staskjs/vue-slick#45
So this works around the issue by destroying and recreating the slick instance when the items change.
resolves https://github.com/uPortal-contrib/uPortal-web-components/issues/31
@rmathis suggestions on getting typescript to pick up on `this.$refs.slick`?

fix: content carousel

---

@uportal/content-carousel/src/components/ContentCarousel.ts

default assignment breaks vue property decorator.

fix(content-carousel): vue property decorator type annotations

---

@uportal/content-carousel/README.md
@uportal/content-carousel/src/App.vue
@uportal/content-carousel/src/components/ContentCarousel.html
@uportal/content-carousel/src/components/ContentCarousel.ts
CHANGELOG.md

passthrough mode allows arbitary content to be turned into a carousel.

feat(content-carousel): add passthrough mode

---

@uportal/content-carousel/src/components/ContentCarousel.ts

Component now renders on Firefox with the Web Component build

fix(content-carousel): update slick slide selector to use vue element

---

@uportal/content-carousel/src/components/ContentCarousel.html

Allows sample RSS provided by @jonathanmtran to render links and styles
#67 will improve appearance of complex text slides.

feat(content-carousel): render description content as html

---

@uportal/content-carousel/src/lib/PortletStrategy.ts

This solution will work for most folks.  There are a very few uPortal implementations that deploy uPortal to the ROOT context of Tomcat (at least there have been).
For future consideration, a better solution would either...
- Detect the `contextName` (either `/uPortal`, `/`, or something else entirely) based on the current page URI;  or
- Provide a `contextName` property -- with a default value of `/uPortal` -- that can be overridden in the custom element markup.

fix: implement 'destinationUrl' in the data model for PortletStrategy

---

COMMITTERS.md

Invite sent as collaborator, until one of the steering committee members can invite him to the uportal-contrib organization.

docs: add Julien as a committer

---

@uportal/esco-content-menu/src/components/ContentGrid.vue

helper needs this to allow base URL to be customized

fix(esco-content-portlet): setup contextApiUrl inside the content grid

---

@uportal/content-carousel/package.json
@uportal/esco-content-menu/package.json
@uportal/eyebrow-user-info/package.json
@uportal/open-id-connect/package.json
@uportal/portlet-registry-to-array/package.json
@uportal/waffle-menu/package.json
docs/en/developer/RELEASE.md
lerna.json
package.json

Why?
* The build now takes longer than 30 seconds, the publish step uses a one time password (otp) to verify the publisher, the otp lasts only 30 seconds, meaning the publish will partially fail or completely fail.
* Conventional commits can be used to determine next version, this automates the version number process.
* Documents the process so hopefully more people can cut releases going forward.

build: update release process

---

@uportal/waffle-menu/package-lock.json
@uportal/waffle-menu/package.json
@uportal/waffle-menu/public/index.html
@uportal/waffle-menu/src/index.js

temporarily switches to a fork of reactive elements until an official version is released.
fixes #86

fix(waffle-menu): web component standard version 1 support

---

@uportal/esco-content-menu/src/components/ContentGrid.vue

This change adds `rel="noopener noreferrer"` to the hyperlinks surrounding `<portlet-card>` elements in the `esco-content-grid`.
https://www.reddit.com/r/SEO/comments/74pwws/rel_noopener_noreferrer_what_does_this_one_do/

fix:  add rel='noopener noreferrer' for links with target='_blank'

---

@uportal/content-carousel/babel.config.js
@uportal/esco-content-menu/babel.config.js
@uportal/esco-content-menu/src/i18n.js
@uportal/eyebrow-user-info/babel.config.js
@uportal/eyebrow-user-info/src/i18n.js
@uportal/open-id-connect/babel.config.js
@uportal/portlet-registry-to-array/babel.config.js

expect adopters to apply the polyfills they want/need to the page.
E.G. uPortal now includes webcomponentsjs, core-js, and regenerator-runtime by default.

refactor: extract polyfills

---

@uportal/eyebrow-user-info/babel.config.js

The build since `vue@cli-service` update to version 3.0.5 doesn't work as expected, it produce a not working component.
The change into `cli-service` is related to [this commit](https://github.com/vuejs/vue-cli/commit/da649385501ff1a9a75bbf286c9f03b14ddce4f1) which is related to [this issue](https://github.com/vuejs/vue-cli/issues/2637)

fix(eyebrow-user-info): vue@cli-service error due to babel helper

---

package.json

`prettier-stylelint --write` rewrite on empty scss files so I moved to prettier native command for such files.
Also a warning about prettier-stylelint, it doesn't have any more activity (1 year last activity), it use a deprecated command postcss. Instead use a such command (the parser option seems not needed on last version of prettier)
```
$ prettier --write --parser scss ./file.scss
$ prettier --write --parser css ./file.css
```
I didn't find an other tool for scss files.

fix: prettier-stylelint isn't active and cause problems on scss files

---

@uportal/esco-content-menu/src/components/ContentGrid.vue

Allows esco content grid header pieces to be removed or replaced via slots.

feat(esco-content-menu): slot grid header

---

@uportal/esco-content-menu/src/icons.js
CHANGELOG.md

webpack was not correctly identinifying unused icons, leading to 700kb of unused icons being included in package.
See: https://github.com/FortAwesome/vue-fontawesome#tree-shaking-alternative

 fix: manually tree shake font awesome icons

---

@uportal/content-carousel/babel.config.js
@uportal/content-carousel/package-lock.json
@uportal/content-carousel/package.json
@uportal/esco-content-menu/babel.config.js
@uportal/esco-content-menu/package-lock.json
@uportal/esco-content-menu/package.json
@uportal/eyebrow-user-info/babel.config.js
@uportal/eyebrow-user-info/package-lock.json
@uportal/eyebrow-user-info/package.json
@uportal/open-id-connect/package-lock.json
@uportal/portlet-registry-to-array/package-lock.json
@uportal/waffle-menu/package-lock.json
package-lock.json

plugin is no longer needed with Babel 7.
Babel 7+ will correctly handle extending built ins.

build: remove babel tranform custom element classes

---

@uportal/esco-content-menu/public/browseable.json
@uportal/esco-content-menu/src/components/ContentGrid.vue
@uportal/esco-content-menu/src/components/ContentMenu.vue
@uportal/esco-content-menu/src/services/sortByPortlet.js

if an "escoMenuOrder" parameter is provided that will be used to sort the element.
If no custom order is provided it will sort by the title in the browsers current locale.
When there is a mix of custom order and title order, custom order will be moved in front of title order.

feat(esco-content-menu): support sort by custom portlet order

---

@uportal/esco-content-menu/src/components/ContentGrid.vue
@uportal/esco-content-menu/src/components/ContentMenu.vue
@uportal/esco-content-menu/src/services/fetchFavorites.js
@uportal/esco-content-menu/src/services/flattenFavorites.js

allow esco content grid to pull in favorites when it is not wrapped by esco content menu.
resolves #163

feat(esco-content-menu): extract favorites to a helper

---

@uportal/esco-content-menu/src/App.vue
@uportal/esco-content-menu/src/components/ActionFavorites.vue
@uportal/esco-content-menu/src/components/ContentFavorites.vue
@uportal/esco-content-menu/src/components/ContentGrid.vue
@uportal/esco-content-menu/src/components/ContentMenu.vue
@uportal/esco-content-menu/src/components/Ellipsis.vue
@uportal/esco-content-menu/src/services/toggleArray.js

Full suite of components still work together
Grid can now update favorites icon when running independent of menu

feat(esco-content-menu): allow favorites to update when grid is run independently

---

@uportal/open-id-connect/package-lock.json
@uportal/open-id-connect/package.json
package-lock.json
package.json

Fixes vulnerability: dominictarr/event-stream#116
See mysticatea/npm-run-all#150 (comment)

chore: bump npm-run-all version to fix vulnerability on sub dependency

---

COMMITTERS.md

Removed Julien from additional contributor list, he now has access through the uPortal committer list.
//cc @mindblender

docs: add Jeff Sittler to committers

---

@uportal/esco-content-menu/README.md
@uportal/esco-content-menu/package-lock.json
@uportal/esco-content-menu/package.json
@uportal/esco-content-menu/src/components/ContentMenu.vue
@uportal/esco-content-menu/src/components/ContentUser.vue
@uportal/esco-content-menu/src/components/HamburgerMenu.vue
@uportal/esco-content-menu/src/services/fetchUserInfoAndOrgs.js
@uportal/esco-content-menu/src/services/organizationHelper.js

Add a better way to configure attribute path from component props using lodash

feat(eco-content-menu): retrieve configurable deep attributes

---

@uportal/content-carousel/babel.config.js
@uportal/content-carousel/package-lock.json
@uportal/content-carousel/package.json
@uportal/content-carousel/src/App.ts
@uportal/content-carousel/src/components/ContentCarousel.ts
@uportal/esco-content-menu/babel.config.js
@uportal/esco-content-menu/package-lock.json
@uportal/esco-content-menu/package.json
@uportal/eyebrow-user-info/babel.config.js
@uportal/eyebrow-user-info/package-lock.json
@uportal/eyebrow-user-info/package.json
@uportal/open-id-connect/package-lock.json
@uportal/portlet-registry-to-array/package-lock.json
@uportal/waffle-menu/package-lock.json
@uportal/waffle-menu/package.json
package-lock.json
package.json

babel preset vue app now force sets compatibility to new browsers only.
this switched vue preset app out for babel preset env, which allows better customization.
Related to https://github.com/vuejs/vue-cli/issues/3096

build: improve backwards compatibility

---

@uportal/dashboard-carousel/package-lock.json
@uportal/dashboard-carousel/package.json
@uportal/dashboard-carousel/src/App.vue
package-lock.json

This PR fixes an issue with the `layoutApiUrl` property when dashboard-carousel is fully built & used as a Web Component.
The most important change is passing `src/components/DashboardCarousel.vue` (the path to the dashboard-carousel source) as an argument to `vue-cli-service build` within the `build` script.  This difference seems to make `DashboardCarousel.vue` the root of the built component, rather than `main.js`.  The former allows `layoutApiUrl` to be overridden, where the latter provides a hard-coded value of `layout.json`.

fix(dashboard-carousel): troubleshoot layoutApiUrl prop

---

@uportal/dashboard-carousel/package.json

all the files are already present.
`main` provides a shortcut for npm and webjars to find the entrypoint without providing the full path.

build(dashboard-carousel): declare source and main files in package

---

@uportal/dashboard-carousel/README.md
@uportal/dashboard-carousel/src/components/DashboardCarousel.vue

Allow the selected region for the carousel to be configured via the `region` attribute on the element.

feat(dashboard-carousel): configurable selected region

---

@uportal/esco-content-menu/src/components/ContentMenu.vue

Reapply styling removed from #197, but apply it from parent as it depends on parent integration.
NOTE: '/deep/' is deprecated in css, but is converted by vue-loader and scss processor.

fix(esco-content-menu): revert css change from #197 but from parent

---

@uportal/content-carousel/src/components/ContentCarousel.ts
@uportal/content-carousel/src/lib/AuthenticatedRssStrategy.ts

This is an attempt at providing an authenticated RSS strategy as described in #170. If there's a cleaner way to implement this, please advise.
closes #170

feat(content-carousel): implemented authenticated RSS strategy

---

@uportal/api-template-vue/src/components/ApiTemplateVue.vue

This change to the `api-template-vue` makes working with data from the specified API easier.  It wraps the JSON received from the API URI in a JavaScript object like this:  `data: () => ({ data: this.json })`.
As a consequence, the variable `data` is guaranteed not to be `undefined`.
Technically this would be a breaking change;  but AFAIK there is exactly one implementation of the `api-template-vue` _in the wild_ and I am updating it.

feat: wrap the JSON returned by the specified API URI

---

@uportal/api-template-vue/src/components/ApiTemplateVue.vue
package-lock.json

By default, `axios.get()` throws an error (rejecting the promise) when it receives a non-200 series status code.  That's not good for us (esp. the `api-template-vue`), since REST APIs commonly use status codes to signify... status.

fix: make axios resove promises even for non-200 status

---

@uportal/user-profile-menu/src/components/ProfileMenu.vue

Fixed widget so that if a slot is empty (using :empty css selector), it does not get displayed.

fix: fixed issue where empty slots were still displayed

---

@uportal/dashboard-carousel/src/components/DashboardCarousel.vue

Set max-width of content items for dashboard-carousel widget to 33% to avoid odd sizing issues.
Added CSS variables for sizing dashboard-carousel buttons (font/padding size).

fix: fixed size of dashboard content items & css variables for buttons

---

@uportal/waffle-menu/README.md
@uportal/waffle-menu/src/components/WaffleMenu.vue
docs/en/components/waffle-menu/README.md

This had some fix with the use of the AlternativeMaximizedLink and add a property to be able to customize the uPortal contact URL on portlet url.

fix: use wrong param AlternativeMaximizedLink + improvements

---

@uportal/waffle-menu/package.json

I hope that these changes will clear up the issues I'm having when I publish the `waffle-menu` webjar.

chore: update 'build' script and 'source' setting to match other modules

---

@uportal/esco-content-menu/public/portletRegistry.json
@uportal/esco-content-menu/src/components/ContentFavorites.vue
docs/en/components/esco-content-menu/portletRegistry.json

The recursion cause a slowed down UI loading and on some browsers that doesn't detect js recursion it can slow down the browser consequently !
This is due to the swipper component used in the favorite-content component (a sub-component of the content-menu and so the hamburger-menu) and the call of the update method that refresh the swipper to have a calculated/adapted size from the available space. The problem was that the update should not be applied until favorites are empty or not loaded !

fix (esco-content-menu): Fix recursion on swipper

---

@uportal/esco-content-menu/README.md
@uportal/esco-content-menu/src/components/ContentGrid.vue
@uportal/esco-content-menu/src/components/PortletCard.vue
@uportal/esco-content-menu/src/services/sizeTools.js
@uportal/esco-content-menu/src/styles/vars.scss

This adds a new option for the esco content grid to provide custom css variables to control various pieces of the grid's cards/items.

feat: custom content card size

---

@uportal/esco-content-menu/README.md
@uportal/esco-content-menu/public/index.html
@uportal/esco-content-menu/src/App.vue
@uportal/esco-content-menu/src/components/ContentFavorites.vue
@uportal/esco-content-menu/src/components/ContentGrid.vue
@uportal/esco-content-menu/src/components/ContentMenu.vue
@uportal/esco-content-menu/src/components/ContentUser.vue
@uportal/esco-content-menu/src/components/HamburgerMenu.vue
@uportal/esco-content-menu/src/i18n.js
@uportal/esco-content-menu/src/locales/en-US.json
@uportal/esco-content-menu/src/locales/fr-FR.json
docs/en/components/esco-content-menu/README.md

This provide some improvments :
- the possibility to set css variable on the content-grid
- the possibility to remove the content-user from the esco-content-menu via slot
- the possibility to remove the header-buttons from esco-content-menu via slot
- the possibility to switch from a slider to the content-grid for the favorite part into esco-content-menu, and from the esco-hamburger-menu
- fix language detection, based on main document lang property (this permit to be based on the uPortal lang definition).

providing some improvements on esco-content-menu

---

@uportal/esco-content-menu/src/components/ContentGrid.vue

from the search term `adm` the default matcher make ranked search like a such request  `%a%d%m`, when moving to `ACRONYM` it will try to do it only on each first word letter.
Results are a bit more fined, and more understandable for users.

fix(content-grid): set matchSorter to ACRONYM

---

@uportal/esco-content-menu/README.md
@uportal/esco-content-menu/src/App.vue
@uportal/esco-content-menu/src/components/ActionFavorites.vue
@uportal/esco-content-menu/src/components/ContentGrid.vue
@uportal/esco-content-menu/src/components/ContentMenu.vue
@uportal/esco-content-menu/src/components/HamburgerMenu.vue
@uportal/esco-content-menu/src/components/PortletCard.vue
@uportal/esco-content-menu/src/mixins/i18n.js

Added support for passing in a json string for customizing the i18n messages. Also separated the i18n logic into a mixin for all components to use.

feat: added support for custom i18n messages

---

docs/en/components/content-carousel/demo.html
docs/en/components/dashboard-carousel/demo.html
docs/en/components/esco-content-menu/demo.html
docs/en/components/waffle-menu/demo.html

defer scripts.
use latest version of core js bundle.
include vue in waffle menu demo.

docs: update demo page dependencies

---

@uportal/esco-content-menu/src/components/ActionFavorites.vue

The onClick on the fav icon is propageted on parent elements whereas it's not required (even for the content-grid) as a callback function entry is provided to manage the action.

fix: avoid Favorites click propagation

---

COMMITTERS.md

Chris Beach is now a uPortal committer, removing duplicated entry here.
Jeff is no longer an active committer to the project, moving him to Emeriti category

docs: update committers

---

@uportal/esco-content-menu/src/components/ActionFavorites.vue

Use isFavorite function for reactivity as only the prop isFavorite is watched and due to loading order the data favorite is not updated after his init. So the best is to use a computed function that add (automatically) a watcher on the prop and maintain the update.
This commit fix #405

fix (esco-favorite-action): favorite data not watched

---

@uportal/content-carousel/README.md
@uportal/content-carousel/src/components/ContentCarousel.scss

Replaces PR #436 
Uses a CSS variable to control the display of the grey hero text banner at the bottom of slides.
Note:  IE is not honoring the CSS variable.
#438 and #439 found while testing this change.

feat(content-carousel):  CSS var to control the display of the hero text

---

@uportal/esco-content-menu/src/components/ActionFavorites.vue
@uportal/esco-content-menu/src/styles/common.scss

provide a sr-only class that isn't applied on builded components.
fix #438

fix(esco-content-menu): style favorite sr-only

---

@uportal/esco-content-menu/public/portletRegistry.json
@uportal/esco-content-menu/src/components/ContentUser.vue
docs/en/components/esco-content-menu/portletRegistry.json
docs/fr/components/esco-content-menu/portletRegistry.json

The user-info-portlet-url where to redirect the user to obtain account details wasn't applied when the user didn't defined an avatar.

fix(esco-content-menu): missing user info link

---

@uportal/dashboard-carousel/src/components/Carousel.vue

Presently, when viewing the dashboard carousel in a mobile viewport, it renders as follows:
This PR sets the `max-width` of the div inside `slick-item` to its initial value of `none` and adds a `bottom-margin` of `10px` such that it renders as such
Let me know if I missed anything and/or if there are any use cases that need to be considered.

fix(dashboard-carousel): added max-width & margin-bottom rules for mobile viewports

---

@uportal/esco-content-menu/README.md
@uportal/esco-content-menu/package-lock.json
@uportal/esco-content-menu/src/components/ContentGrid.vue

Add "preamble" div between headers and grid for explanatory text.
Implemented with a slot. Styling and doc updated.

feat(esco-content-grid): add preamble slot

---

@uportal/sidebar-nav/package.json

Due to '*' in build script, web component tag was `<sidebar-nav-sidebar-nav>`. Specifying the component, corrects the expected tag name to `<sidebar-nav>`

fix(sidebar-nav): update build in package.json to correct name of tag

---

@uportal/waffle-menu/src/components/WaffleMenu.vue

This pull request adds 3 accessibility enhancements

Waffle menu/accessibility enhancements

---

@uportal/esco-content-menu/README.md
@uportal/esco-content-menu/src/App.vue
@uportal/esco-content-menu/src/components/ContentGrid.vue
@uportal/esco-content-menu/src/components/ContentMenu.vue
@uportal/esco-content-menu/src/components/PortletCard.vue

Configure optional `title` text for grid portlet-cards for display when hovering. Source can be `none`, portlet `title`, or portlet `description`.
README updated

feat: add hover text to cards based on portlet title or desc

---

@uportal/esco-content-menu/src/components/ContentGrid.vue

Reverting how categories are determined via computed function

fix(esco-content-grid): revert categories to computed func

---

@uportal/grid-carousel/src/grid-carousel.js
CHANGELOG.md

This fix adds a missing title attribute to the links in the grid-carousel component

fix: added missing title attribute to grid carousel links
